version: '3'
services:

  backend:
    depends_on:
      - tika
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"

  frontend:
    depends_on:
      - backend
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8002:8002"

  tika:
    image: apache/tika
