CLASSIFIER_PATH = "models/model_v1.pkl"
CLASSIFIER_PATH_PATH_TO_OLD_DATA = "data/train.csv"
CLASSIFIER_TEST_SIZE = 0.1
CLASSIFIER_RANDOM_STATE = 42


PARSER_TIKA_SERVER = "tika:9998"


TOPIC_MODELER_PATH_TO_DATASET = "data/topic_modeling_dataset"
TOPIC_MODELER_NUM_TOPICS = 15
TOPIC_MODELER_PHI = 0.3
TOPIC_MODELER_THETA = 0.1
TOPIC_MODELER_SEED = 21
TOPIC_MODELER_PASS_TO_ORIGINAL_CORPUS = "data/topic_modeling.txt"